### PR TITLE
feat: stage 3

### PR DESCRIPTION
**Pull request by reginleiff**
Things you should know while play-testing this level:
- You finish the stage when you reach the end of the bridge with railings (entry to stage 4 - tower)
- Puzzles are not intended to have a specific solution
- Have not put any fancy lighting or fadeout blocks yet - waiting for puzzles and designs to be approved first
- Blocks falling at the beginning of the level is intended cuz it looks cool (but tell me what you think)

Any feedback is appreciated especially puzzles.

### CODE REVIEW

**Comment by nicholaschuayunzhi** [comment]
There are two blocks in one spot here:
image

**Comment by reginleiff** [comment]
Will be finding time to rework stuff in the stage tomorrow before moving on to another level, let me know on anything I can improve on!

@teclu @nicholaschuayunzhi @Rinder5 @jo-lyn @saho-london

**Comment by nicholaschuayunzhi** [comment]
Things that can be improved
- less sand
- use disintegrate block more meaningfully (i like the first part though, its a good intro to it)
- last part of the level seems brain dead to solve
- update the lighting / background, use post processing
- remove duplicate blocks

**Comment by nicholaschuayunzhi** [comment]
hi @reginleiff before you finish, remember to resolve the conflict in the plugin arising from #101

**Pull request merged**
