### PR TITLE
feat: new tutorial

### PR DESCRIPTION
**Pull request by reginleiff**
The old tutorial converts into stage 0, while this is the new tutorial. I'm thinking of how to link this new tutorial with stage 0 (we could do a special scene transition) and whether to do a small house scene for movement controls.

Tell me what you think.

### CODE REVIEW

**Comment by nicholaschuayunzhi** [comment]
Is the tutorial complete? Doesn't seem to have set steps to follow (most of it seems to be free form). Or are you planning to use speech bubbles to guide?

**Comment by reginleiff** [comment]
Yes it is rather complete for now, since I think there is no need for an internal movement tutorial, it can be just done outside of the house porch.

We will have to use speech bubbles to guide. I could take another approach where we force the player to just take one route and use speech bubbles but I think that it may be too out of context of the direction of the game. I can do another one (the more straightforward type) and maybe perhaps you guys can pick on Sunday.

**Comment by nicholaschuayunzhi** [comment]
Let's decide before this weekend. Personally I understand what you mean by:

> too out of context of the direction of the game

If that's the case, maybe the speech bubbles must be very instructive (but even then its also not the direction we want). Maybe we can hide it with some story?

What do you guys think @Rinder5 @jo-lyn @teclu

**Comment by reginleiff** [comment]
I think the idea we had concluded with last Sunday was that we would use the speech bubbles to **hint** at an objective. (E.g. "The castle wall lies over this cliff..."). 

Additionally, if we are able to put images in the speech bubbles, images combined with speech can be used to explain her limitations. (E.g. we show an image of her pulling a block with a highlighted LMB click - our poster picture works well here - and then along with "Teacher only taught me to be able to pull a block out once...").

Of course, let me know what you guys think about it.

**Comment by Rinder5** [comment]
I thought we concluded that speech bubbles would be used to tell the story? 0.o

**Comment by reginleiff** [comment]
@Rinder5 Yup so the speech bubbles explain the purpose (story), but are reinforced with the guiding collectibles.

Since the tutorial phase is only like 2 minutes, I figure we can use the speech bubbles for explaining her abilities so that we can save time on work (if the implementation permits).

Alternatively we can just do an overlay that shows all the available keys which disappears after they press all of the keys in a sandbox setting. I think this is the most in-your-face strategy, but I think we overruled this as no-go on Sunday iirc.

**Pull request merged**
