### PR TITLE
feat: level-tuning

### PR DESCRIPTION
**Pull request by reginleiff**
- Update stage 2 to have secondary collectibles
- Add stage 2 puzzle 4 - tunnel to block light
- Update stage 3 with respect to above changes

@Rinder5 @teclu @jo-lyn @nicholaschuayunzhi FEEDBACK PLS THX

### CODE REVIEW

**Comment by nicholaschuayunzhi** [comment]
# Some Comments

Really enjoyed playing through all of your puzzles. I have left some comments here. If we need to get things moving, I'll merge this but feel free to make a new pr for these if necessary.

Thank you so much for the hardwork. The levels were really fun. Especially the new stage_2 ones.

---
image

Did you intentionally change the top layer to full grass blocks?

---
image

Are we allowing two secondaries per level? @Rinder5 does your UI support this?

---
image

image


Previous levels here unloads at these line. Is it possible to give more lee way?

---
image

Is this puzzle going to be updated?
___

**Comment by nicholaschuayunzhi** [comment]
I will be merging so that we can work on the scenes.

**Comment by Rinder5** [comment]
@nicholaschuayunzhi right now it doesn't, but i can update it so it can

**Comment by Rinder5** [comment]
however, those two being so close together makes it more suitable for primaries?

**Pull request merged**
