### PR TITLE
feat: stage 1

### PR DESCRIPTION
**Pull request by teclu**
**Level Overview**:
image

**Puzzle 1**:
image
Break the gravel block and pull the sand blocks into the hole made.

image
Fall into the hole to land on the fallen sand blocks, and jump over to the next part of the level. Hopefully this is not too hard?

**Puzzle 2**:
image

image

This puzzle involves several steps, but the general idea is to shift away sand blocks from the 1 block-height entrance:

image

Which leads into the caverns-theme for stage 2.

### CODE REVIEW

**Comment by nicholaschuayunzhi** [comment]
Did you change the normal bias of the directional light in tutorial scene to 0? The light in the corner of the wall still leaks through.

**Comment by nicholaschuayunzhi** [comment]
I think the first puzzle make sense. I dont get where to go with the 2nd one.

**Comment by teclu** [comment]
@nicholaschuayunzhi my bad ahh x_x, will change the normal bias! I think that the second one may be too hard, but my initial design for it was too simple... 😣

**Comment by nicholaschuayunzhi** [comment]
Dont sweat it! Overall i think it looks good! Could you share what was your original plan?

**Review by nicholaschuayunzhi — APPROVED** [review]
Looks good! We can slowly begin to work on the signposts + checkpoints +stage transition

**Pull request merged**
