### PR TITLE
feat: redesigned tutorial stage

### PR DESCRIPTION
**Pull request by teclu**
image

This is a follow up of #51.

**Changes made:**
- Level is now linear.
- Wall puzzle does not use sand blocks anymore. A moveable stone block of a different tint is used (_however, will need an atlas for the UV mapping_).
- Gravel is now used at the ditch crossing. There are 3 chances for the player to cross over.
- The platforming part no longer has a "safety net" below; players can figure out that falling off the platforms result in their demise.

**To be done in the future**:
- Decorative objects need to be placed in the stage to liven things up.

### CODE REVIEW

**Comment by nicholaschuayunzhi** [comment]
@teclu,I found a bug, originating from my player move block  script. Don't put moveable plugins onto gravel blocks atm. If timed poorly, the player will be destroyed with the block T_T

Will have to fix it asap.

EDIT: FIxed in https://github.com/this-place/this.place/pull/84

**Comment by nicholaschuayunzhi** [comment]
Some comments:
- This stage seems a bit too big for what it is showcasing
- did not notice the stairs next to to the pit, maybe we can have the stairs in the middle?
- controls feel bad so i can't really make a good judgement  (As well as review) on the jumping at the end

**Comment by reginleiff** [comment]
Comments:
- This is still fine although I don't like this castle as much as the previous as it is much bigger for not much reason (we had planned for levels to be compact?). My suggestion is that maybe we can just make it such that she escapes through a tower section of the wall since you cut off the portion behind the player. It's a great opportunity for the player to explore and get used to the rotation features and platforming feeling.

- Why three gravel bridges? To explore the behaviour?

- Is the final portion meant to teach jump-pull? I may get stuck there if I don't know that I can do that.

- I think the move-able stone block was bound to be coming sooner or later for aesthetic purposes but this means we need to do one of the following:
1. Make it clear that we are able to pull blocks that we can highlight instead of a specific block type which we have previously planned - pretty big deal because it means there will be immovable dirt etc. If this is the case then even the ditch that the player falls in can be made of immovable dirt. As for this level so far, it may not be as intuitive so perhaps think of a way to better incorporate that idea in.

2. New block: We can just label this block `clay` or something. Other alterations of current blocks will also have their new names and textures.

**Comment by teclu** [comment]
I've taken note of your comments guys. In particular,

> "This stage seems a bit too big for what it is showcasing"
> "it is much bigger for not much reason"

Will make it smaller. Initially wanted to put decorations to make it feel less empty, but I guess that can be done next time.

> "did not notice the stairs next to to the pit, maybe we can have the stairs in the middle?"

Good idea; will do this and make the level cleaner (less blocks sticking out of the sides of the stage).

> "Why three gravel bridges? To explore the behaviour?"

Yes, but my fear is that if there was only 1 bridge, some players may destroy it completely and not be able to cross over with ease. Maybe 3 is a bit too much?

> "Is the final portion meant to teach jump-pull? I may get stuck there if I don't know that I can do that."

Yes. Jump-pull is also possible at the wall section (should have added a screenshot of this, my bad). Probably need testers to try this to see if it's obvious enough (or not).

Will be making the changes ASAP today. Thanks for the help @nicholaschuayunzhi and @reginleiff!

**Comment by teclu** [comment]
**Update to Layout:**

image

@nicholaschuayunzhi @reginleiff is this size more appropriate? Also, I have made the staircase in the middle and only used 2 gravel bridges.

**Comment by nicholaschuayunzhi** [comment]
looks better 👍 . I feel like the starting puzzle is not very obvious though. But i think it can be managed by some text system.

**Comment by reginleiff** [comment]
@teclu Is the final part meant to be solvable without using the sand blocks?

Also, yeah the size is much better!

> I feel like the starting puzzle is not very obvious though.

Yes, it does seem like the hardest part of the level is ironically at the beginning. Not sure if you can fit the final wall part at the end but it may be a solution.

**Comment by teclu** [comment]
@reginleiff wasn't intentional; will make a small change to it! As for the wall puzzle, I will make it simpler.

**Comment by teclu** [comment]
image

- Wall puzzle is now easier; minimum of 2 pulls.

image

- The sand block pull is now the only way to get to the top. The surrounding grass blocks are not moveable.

image

- Idea for the "end" of the stage; maybe use a simple rock with emitters to make things look cool.

image

- Overall layout with trees and rocks. The grass blocks that are surrounding the stairs, or have trees/rocks on them are not moveable.

**Comment by nicholaschuayunzhi** [comment]
this looks great 👍 @reginleiff any thoughts?

**Review by reginleiff — APPROVED** [review]
**Gr8 m8 8/8**

I think the deco is really good and it doesn't hurt to add more. We can re-touch this in the polishing phase, so I think we can merge this for now. @nicholaschuayunzhi

**Pull request merged**
