### PR TITLE
feat: tutorial stage

### PR DESCRIPTION
**Pull request by teclu**
w.r.t. #51 

image

**First Update**: Basic layout of the tutorial stage which will introduce the concepts of displacement and platforming.

**Edit**: Will extend this stage further in this PR.

### CODE REVIEW

**Review by reginleiff — CHANGES_REQUESTED** [review]
It's looking good so far but its still far from being incomplete so I'll hold back on the full review until you give the green light.

Some comments:
- The second part after the wall cannot work with the new displace mechanic so KIV.

- The initial section requires the act of pulling the block out from the ground in front of the character, but I think it may be better to start off with pulling blocks out of the wall then go into that. You could design all of these in one section or multiple.

**Comment by teclu** [comment]
Hi @reginleiff, for the second part I intend to have the player attempt a platform jump by raising 1-2 blocks first, and then running and jumping over to the other side.

As for the initial (wall) section, that can certainly be done. I would probably give players both options so that they know that they can pull from either the ground and wall.

**Comment by reginleiff** [comment]
Ah, yes I see. Okay then maybe we can include a section with a long jump before that section just to ease him into the solution. It is the tutorial after all.

**Comment by teclu** [comment]
image

Second Update: Taking into account of @reginleiff's suggestions, here is how the tutorial stage is like:

1. Sand blocks (until we get another material) will be pulled out of the wall, so that players can climb over it.

2. A short distance platform jump to ease them into the jumps required at part 3.

3. A slightly harder jump area where blocks need to be pulled in the first jump, and a "dash/sprint" is needed to clear the next jump.

4. To let players discover about the gravel block (fragile mechanic); even if they somehow fail to cross over the platform and destroy all the gravel blocks, it is still easy for them to jump across.

5. Lastly, show the players how the sand block (gravity mechanic) works. Ideally, when they pull the bottom row of sand blocks, they will create a "staircase" to get them to their end goal.

**Comment by nicholaschuayunzhi** [comment]
> A slightly harder jump area where blocks need to be pulled in the first jump, and a "dash/sprint" is needed to clear the next jump.

Are you suggesting a sprint mechanic? Or acceleration for the char?

**Comment by nicholaschuayunzhi** [comment]
For the stage highlighted at *2*, are those 2 half blocks?

**Comment by teclu** [comment]
> Are you suggesting a sprint mechanic? Or acceleration for the char?

Yeah, like hold shift to run faster. Or maybe just increase the acceleration/max speed! 

No half-blocks were used in the level.

**Comment by nicholaschuayunzhi** [comment]
@teclu I realised why it felt so weird. Set camera to orthographic for the isometric feel.

**Review by reginleiff — APPROVED** [review]
Its good @teclu. Do you have any idea how section 5 will lead into stage 1? Section 3 to 4 requires that sprint for now, so maybe you can create an issue for it.

**Comment by teclu** [comment]
I have a rough idea of how stage 1 would look like, but I have not fleshed it out completely on Unity. As requested, I have created a new issue (#75) for Character Sprint/Run. Thanks for the review! ^_^

**Pull request merged**
