### PR TITLE
feat: bouncing block

### PR DESCRIPTION
**Pull request by jo-lyn**

### CODE REVIEW

**Comment by nicholaschuayunzhi** [comment]
@jo-lyn to clarify is this the AI we're making and not a block

**Comment by jo-lyn** [comment]
Noted 👍  I attached the block behavior script to the AI as blocks around it cannot be interacted with otherwise. Will this interfere with what we will be doing with it, or is there a workaround?

**Comment by nicholaschuayunzhi** [comment]
some screen shots:

image

**Comment by nicholaschuayunzhi** [comment]
The collider doesnt seem to match the block. Is this intended?

image

**Comment by jo-lyn** [comment]
Yea, without it the player could be squashed underneath 🤣

**Comment by nicholaschuayunzhi** [comment]
> I attached the block behavior script to the AI as blocks around it cannot be interacted with otherwise. Will this interfere with what we will be doing with it, or is there a workaround?

I think how you implemented it is fine. Once the block dies, we can make sure it dies correctly and remove the animator component (may not be required).

Remember to remove the Bounce Scriptable Object instance.

**Comment by nicholaschuayunzhi** [comment]
> Yea, without it the player could be squashed underneath

Hmm actually that could be fine considering we want the player restart if the block chases after them. But i think we can leave it here first.

**Review by nicholaschuayunzhi — APPROVED** [review]

**Pull request merged**
