### PR TITLE
fix: camera doesn't flip

### PR DESCRIPTION
**Pull request by Rinder5**

### CODE REVIEW

**Comment by nicholaschuayunzhi** [comment]
Does this ensure that the camera never flips?

**Comment by Rinder5** [comment]
yes* (it still uses the old implementation style i used for autozoom, so it might still flip. but significantly less possible)

**Comment by nicholaschuayunzhi** [comment]
> so it might still flip

Is this avoidable?

**Comment by Rinder5** [comment]
yea, but it requires a bit more math. this was just a quick fix

**Pull request merged**
